import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { createClient } from '@supabase/supabase-js';
import { InvoiceEmailData } from './emailService.js';

const SUPABASE_URL = process.env.SUPABASE_URL || "https://dfqvgezjhudmnlyeycju.supabase.co";
const SUPABASE_ANON_KEY = process.env.SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmcXZnZXpqaHVkbW5seWV5Y2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYyNDAyOTMsImV4cCI6MjA4MTgxNjI5M30.8VsHsDpychdSMJmrfnmkxi5ed8CygwErX3-RkVPXkUI";
const supabaseClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const TOKEN_SECRET = process.env.INVOICE_TOKEN_SECRET || process.env.SUPABASE_JWT_SECRET || 'cravebiz_invoice_sec_token_2026_key';

// In-memory caches for rapid PDF retrieval and verification
export const invoiceDataCache = new Map<string, InvoiceEmailData>();
export const invoicePdfBufferCache = new Map<string, Uint8Array>();

// Ensure local invoice uploads directory exists
const isProductionDir = process.env.VERCEL === "1" || process.env.NODE_ENV === "production";
const invoiceUploadsDir = isProductionDir
    ? path.join("/tmp", "uploads", "invoices")
    : path.join(process.cwd(), "uploads", "invoices");

try {
    if (!fs.existsSync(invoiceUploadsDir)) {
        fs.mkdirSync(invoiceUploadsDir, { recursive: true });
    }
} catch (e) {
    console.warn("Failed to initialize invoice storage directory:", e);
}

/**
 * Generates a secure, tamper-proof access token for an invoice download link.
 * Format: <base64url(invoiceId:companyId:timestamp)>.<hmac_sha256>
 */
export function generateInvoiceAccessToken(invoiceId: string, companyId?: string): string {
    const rawPayload = `${invoiceId}:${companyId || 'default'}`;
    const encodedPayload = Buffer.from(rawPayload).toString('base64url');
    const hmac = crypto.createHmac('sha256', TOKEN_SECRET).update(rawPayload).digest('hex').substring(0, 32);
    return `${encodedPayload}.${hmac}`;
}

/**
 * Validates the access token before permitting PDF download.
 * Ensures the invoice ID cannot be tampered with or modified in the URL.
 */
export function verifyInvoiceAccessToken(token: string): { invoiceId: string; companyId: string } | null {
    try {
        if (!token || !token.includes('.')) return null;
        const [encodedPayload, providedHmac] = token.split('.');
        if (!encodedPayload || !providedHmac) return null;

        const rawPayload = Buffer.from(encodedPayload, 'base64url').toString('utf8');
        const [invoiceId, companyId] = rawPayload.split(':');
        if (!invoiceId) return null;

        const expectedHmac = crypto.createHmac('sha256', TOKEN_SECRET).update(rawPayload).digest('hex').substring(0, 32);

        const providedBuf = Buffer.from(providedHmac);
        const expectedBuf = Buffer.from(expectedHmac);

        if (providedBuf.length === expectedBuf.length && crypto.timingSafeEqual(providedBuf, expectedBuf)) {
            return { invoiceId, companyId: companyId || 'default' };
        }
    } catch (err) {
        return null;
    }
    return null;
}

/**
 * Cleans text for pdf-lib standard Helvetica font (WinAnsiEncoding).
 * Replaces non-WinAnsi characters like ₦ and • to prevent encoding exceptions.
 */
export function cleanPdfText(text: string | null | undefined): string {
    if (!text) return "";
    return text
        .replace(/₦/g, "NGN ")
        .replace(/•/g, " - ")
        .replace(/—/g, "-")
        .replace(/–/g, "-")
        .replace(/[“”]/g, '"')
        .replace(/[‘’]/g, "'")
        .replace(/[^\x20-\x7E]/g, "");
}

/**
 * Helper to split text into lines fitting within a max character length
 */
function wrapText(text: string, maxCharsPerLine = 45): string[] {
    if (!text) return [];
    const words = text.split(/\s+/);
    const lines: string[] = [];
    let currentLine = "";

    for (const word of words) {
        if ((currentLine + " " + word).trim().length <= maxCharsPerLine) {
            currentLine = (currentLine + " " + word).trim();
        } else {
            if (currentLine) lines.push(currentLine);
            currentLine = word;
        }
    }
    if (currentLine) lines.push(currentLine);
    return lines;
}

/**
 * Generates the complete, high-fidelity official invoice PDF generated by CraveBiz AI.
 * Contains company logo/details, client info, itemized services, discounts, taxes, totals,
 * settlement bank details, commercial terms, and security protocol branding.
 */
export async function generateInvoicePdfBuffer(data: InvoiceEmailData): Promise<Uint8Array> {
    const pdfDoc = await PDFDocument.create();
    let page = pdfDoc.addPage([595.28, 841.89]); // Standard A4 Size
    let { width, height } = page.getSize();

    const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
    const fontOblique = await pdfDoc.embedFont(StandardFonts.HelveticaOblique);

    // Official CraveBiz Professional Color Palette
    const primaryDark = rgb(0.12, 0.11, 0.29);   // #1e1b4b (Deep CraveBiz Indigo)
    const accentIndigo = rgb(0.31, 0.27, 0.90);  // #4f46e5 (Brand Accent)
    const textDark = rgb(0.11, 0.13, 0.17);      // #111827 (High Contrast)
    const textMuted = rgb(0.42, 0.46, 0.53);     // #6b7280
    const bgLight = rgb(0.97, 0.98, 0.99);       // #f8fafc
    const borderGray = rgb(0.90, 0.91, 0.93);    // #e5e7eb
    const successGreen = rgb(0.09, 0.63, 0.44);  // #16a34a
    const warningAmber = rgb(0.85, 0.45, 0.05);  // #d97706
    const alertRed = rgb(0.88, 0.15, 0.15);      // #dc2626

    const rawSymbol = data.currencySymbol || "₦";
    const symbol = rawSymbol === "₦" ? "NGN " : cleanPdfText(rawSymbol);

    // Determine status & document title
    const isPaid = (data.status === 'Paid') || ((data.amountPaid || 0) >= (data.totalAmount || 0) && (data.totalAmount || 0) > 0);
    const isPartiallyPaid = !isPaid && (data.amountPaid || 0) > 0;
    const documentTitle = isPaid ? "OFFICIAL INVOICE (PAID)" : "OFFICIAL INVOICE";

    let currentY = height - 35;

    // Header Background Block
    page.drawRectangle({
        x: 35,
        y: currentY - 75,
        width: width - 70,
        height: 80,
        color: primaryDark
    });

    // Try embedding company logo if provided
    let logoDrawn = false;
    if (data.company && data.company.logoUrl) {
        try {
            const logoUrl = data.company.logoUrl;
            let imageBytes: Uint8Array | null = null;
            let isPng = false;
            let isJpg = false;

            if (logoUrl.startsWith('data:image/png;base64,')) {
                imageBytes = Buffer.from(logoUrl.replace(/^data:image\/png;base64,/, ''), 'base64');
                isPng = true;
            } else if (logoUrl.startsWith('data:image/jpeg;base64,') || logoUrl.startsWith('data:image/jpg;base64,')) {
                imageBytes = Buffer.from(logoUrl.replace(/^data:image\/jpe?g;base64,/, ''), 'base64');
                isJpg = true;
            } else if (logoUrl.startsWith('http://') || logoUrl.startsWith('https://')) {
                const res = await fetch(logoUrl);
                if (res.ok) {
                    const buf = await res.arrayBuffer();
                    imageBytes = new Uint8Array(buf);
                    const ct = res.headers.get('content-type') || '';
                    isPng = ct.includes('png') || logoUrl.endsWith('.png');
                    isJpg = ct.includes('jpeg') || ct.includes('jpg') || logoUrl.endsWith('.jpg') || logoUrl.endsWith('.jpeg');
                    if (!isPng && !isJpg) isPng = true;
                }
            }

            if (imageBytes) {
                let embeddedLogo;
                try {
                    embeddedLogo = isPng ? await pdfDoc.embedPng(imageBytes) : await pdfDoc.embedJpg(imageBytes);
                } catch {
                    try {
                        embeddedLogo = isPng ? await pdfDoc.embedJpg(imageBytes) : await pdfDoc.embedPng(imageBytes);
                    } catch {}
                }

                if (embeddedLogo) {
                    const dims = embeddedLogo.scaleToFit(90, 40);
                    page.drawImage(embeddedLogo, {
                        x: 50,
                        y: currentY - 60,
                        width: dims.width,
                        height: dims.height
                    });
                    logoDrawn = true;
                }
            }
        } catch (logoErr) {
            console.warn("Logo embedding warning:", logoErr);
        }
    }

    const companyStartX = logoDrawn ? 150 : 50;

    // Company Name in Header
    const companyName = cleanPdfText((data.company?.name || "CRAVEBIZ WORKSPACE").toUpperCase());
    page.drawText(companyName, {
        x: companyStartX,
        y: currentY - 26,
        size: 15,
        font: fontBold,
        color: rgb(1, 1, 1)
    });

    if (data.company?.address) {
        page.drawText(cleanPdfText(data.company.address.substring(0, 60)), {
            x: companyStartX,
            y: currentY - 42,
            size: 8.5,
            font: fontRegular,
            color: rgb(0.80, 0.84, 0.99)
        });
    }

    const contactStr = [data.company?.email, data.company?.phone].filter(Boolean).join(" | ");
    if (contactStr) {
        page.drawText(cleanPdfText(contactStr.substring(0, 60)), {
            x: companyStartX,
            y: currentY - 56,
            size: 8,
            font: fontRegular,
            color: rgb(0.70, 0.75, 0.95)
        });
    }

    // Header Right Badge: INVOICE / DOCUMENT
    page.drawText("DOCUMENT", {
        x: width - 170,
        y: currentY - 24,
        size: 13,
        font: fontBold,
        color: rgb(1, 1, 1)
    });

    page.drawText(cleanPdfText(`# ${data.invoiceNumber}`), {
        x: width - 170,
        y: currentY - 42,
        size: 11,
        font: fontBold,
        color: rgb(0.82, 0.86, 1)
    });

    // Status Pill
    const statusText = isPaid ? "STATUS: PAID" : isPartiallyPaid ? "STATUS: PARTIAL" : "STATUS: ISSUED";
    const statusColor = isPaid ? successGreen : isPartiallyPaid ? warningAmber : rgb(0.85, 0.89, 1);
    page.drawText(statusText, {
        x: width - 170,
        y: currentY - 58,
        size: 8,
        font: fontBold,
        color: statusColor
    });

    currentY -= 95;

    // Billing & Metadata Section (2-column layout)
    page.drawText("BILLED TO:", {
        x: 40,
        y: currentY,
        size: 8.5,
        font: fontBold,
        color: textMuted
    });

    page.drawText(cleanPdfText((data.recipientCompany || data.recipientName || "Valued Client").toUpperCase()), {
        x: 40,
        y: currentY - 14,
        size: 12,
        font: fontBold,
        color: textDark
    });

    let recipientYOffset = 28;
    if (data.recipientCompany && data.recipientName) {
        page.drawText(cleanPdfText(`Attention: ${data.recipientName}`), {
            x: 40,
            y: currentY - recipientYOffset,
            size: 9,
            font: fontRegular,
            color: textDark
        });
        recipientYOffset += 13;
    }

    if (data.recipientEmail) {
        page.drawText(cleanPdfText(data.recipientEmail), {
            x: 40,
            y: currentY - recipientYOffset,
            size: 8.5,
            font: fontRegular,
            color: textMuted
        });
        recipientYOffset += 13;
    }

    if (data.recipientAddress) {
        page.drawText(cleanPdfText(data.recipientAddress.substring(0, 50)), {
            x: 40,
            y: currentY - recipientYOffset,
            size: 8.5,
            font: fontRegular,
            color: textMuted
        });
    }

    // Right Column: Issue & Due Dates
    page.drawText("Issue Date:", {
        x: width - 180,
        y: currentY,
        size: 8.5,
        font: fontBold,
        color: textMuted
    });
    page.drawText(cleanPdfText(data.issueDate || "N/A"), {
        x: width - 100,
        y: currentY,
        size: 8.5,
        font: fontBold,
        color: textDark
    });

    page.drawText("Due Date:", {
        x: width - 180,
        y: currentY - 16,
        size: 8.5,
        font: fontBold,
        color: textMuted
    });
    page.drawText(cleanPdfText(data.dueDate || "N/A"), {
        x: width - 100,
        y: currentY - 16,
        size: 8.5,
        font: fontBold,
        color: isPaid ? textDark : alertRed
    });

    currentY -= 65;

    // Items Table Header
    page.drawRectangle({
        x: 35,
        y: currentY - 18,
        width: width - 70,
        height: 22,
        color: bgLight,
        borderColor: borderGray,
        borderWidth: 1
    });

    page.drawText("SERVICE DESCRIPTION", { x: 45, y: currentY - 12, size: 8, font: fontBold, color: textMuted });
    page.drawText("UNIT", { x: 300, y: currentY - 12, size: 8, font: fontBold, color: textMuted });
    page.drawText("RATE", { x: 360, y: currentY - 12, size: 8, font: fontBold, color: textMuted });
    page.drawText("DISC.", { x: 440, y: currentY - 12, size: 8, font: fontBold, color: textMuted });
    page.drawText("VALUE", { x: 495, y: currentY - 12, size: 8, font: fontBold, color: textMuted });

    currentY -= 26;

    // Table Rows
    const items = (data.items && data.items.length > 0)
        ? data.items
        : [{ name: "Professional Services", quantity: 1, price: data.totalAmount || 0 }];

    let calculatedGross = 0;
    let calculatedLineDiscounts = 0;

    items.forEach((item, index) => {
        // Page break check
        if (currentY < 140) {
            page = pdfDoc.addPage([595.28, 841.89]);
            currentY = height - 40;
            // Redraw small header on continuation page
            page.drawText(cleanPdfText(`Invoice #${data.invoiceNumber} (Continued)`), {
                x: 40,
                y: currentY,
                size: 9,
                font: fontBold,
                color: textMuted
            });
            currentY -= 25;
        }

        const qty = item.quantity || 1;
        const rate = item.price || 0;
        const lineDiscount = item.discount || 0;
        const lineTotal = Math.max(0, (qty * rate) - lineDiscount);

        calculatedGross += (qty * rate);
        calculatedLineDiscounts += lineDiscount;

        const isAlt = index % 2 === 1;
        const descLines = wrapText(cleanPdfText(item.description || ""), 48);
        const rowHeight = Math.max(24, 18 + descLines.length * 10);

        if (isAlt) {
            page.drawRectangle({
                x: 35,
                y: currentY - rowHeight + 6,
                width: width - 70,
                height: rowHeight,
                color: rgb(0.985, 0.985, 0.99)
            });
        }

        // Service Name
        page.drawText(cleanPdfText(item.name || "Service Item"), {
            x: 45,
            y: currentY - 8,
            size: 8.5,
            font: fontBold,
            color: textDark
        });

        // Wrapped Description
        let descY = currentY - 18;
        descLines.forEach((dl) => {
            page.drawText(dl, {
                x: 45,
                y: descY,
                size: 7.5,
                font: fontRegular,
                color: textMuted
            });
            descY -= 9.5;
        });

        // Quantity
        page.drawText(cleanPdfText(String(qty)), {
            x: 305,
            y: currentY - 8,
            size: 8.5,
            font: fontRegular,
            color: textDark
        });

        // Rate
        page.drawText(cleanPdfText(`${symbol}${rate.toLocaleString('en-US', { minimumFractionDigits: 2 })}`), {
            x: 360,
            y: currentY - 8,
            size: 8.5,
            font: fontRegular,
            color: textDark
        });

        // Discount
        const discStr = lineDiscount > 0 ? `-${symbol}${lineDiscount.toLocaleString('en-US', { minimumFractionDigits: 2 })}` : "-";
        page.drawText(cleanPdfText(discStr), {
            x: 440,
            y: currentY - 8,
            size: 8,
            font: fontRegular,
            color: lineDiscount > 0 ? alertRed : textMuted
        });

        // Line Total
        page.drawText(cleanPdfText(`${symbol}${lineTotal.toLocaleString('en-US', { minimumFractionDigits: 2 })}`), {
            x: 495,
            y: currentY - 8,
            size: 8.5,
            font: fontBold,
            color: textDark
        });

        page.drawLine({
            start: { x: 35, y: currentY - rowHeight + 6 },
            end: { x: width - 35, y: currentY - rowHeight + 6 },
            thickness: 0.5,
            color: borderGray
        });

        currentY -= rowHeight;
    });

    currentY -= 15;

    // Calculations for Totals Section
    const grossSubtotal = calculatedGross;
    const overallDiscount = data.discount || 0;
    const totalDiscount = calculatedLineDiscounts + overallDiscount;
    const netSubtotal = Math.max(0, grossSubtotal - totalDiscount);
    const tax = data.tax !== undefined ? data.tax : Math.round(netSubtotal * 0.075 * 100) / 100;
    const totalAmount = data.totalAmount || (netSubtotal + tax);
    const amountPaid = isPaid ? totalAmount : (data.amountPaid || 0);
    const balanceDue = isPaid ? 0 : Math.max(0, totalAmount - amountPaid);

    // Summary Box on Right
    const summaryBoxHeight = amountPaid > 0 ? 115 : 85;
    const summaryBoxY = currentY - summaryBoxHeight;

    page.drawRectangle({
        x: width - 260,
        y: summaryBoxY,
        width: 225,
        height: summaryBoxHeight,
        color: bgLight,
        borderColor: borderGray,
        borderWidth: 1
    });

    let sY = currentY - 14;
    page.drawText("Gross Value:", { x: width - 248, y: sY, size: 8, font: fontRegular, color: textMuted });
    page.drawText(cleanPdfText(`${symbol}${grossSubtotal.toLocaleString('en-US', { minimumFractionDigits: 2 })}`), { x: width - 130, y: sY, size: 8, font: fontBold, color: textDark });
    sY -= 13;

    if (totalDiscount > 0) {
        page.drawText("Discount:", { x: width - 248, y: sY, size: 8, font: fontRegular, color: alertRed });
        page.drawText(cleanPdfText(`-${symbol}${totalDiscount.toLocaleString('en-US', { minimumFractionDigits: 2 })}`), { x: width - 130, y: sY, size: 8, font: fontBold, color: alertRed });
        sY -= 13;
    }

    page.drawText("VAT (7.5%):", { x: width - 248, y: sY, size: 8, font: fontRegular, color: textMuted });
    page.drawText(cleanPdfText(`${symbol}${tax.toLocaleString('en-US', { minimumFractionDigits: 2 })}`), { x: width - 130, y: sY, size: 8, font: fontBold, color: textDark });
    sY -= 16;

    page.drawLine({ start: { x: width - 248, y: sY + 3 }, end: { x: width - 45, y: sY + 3 }, thickness: 0.5, color: borderGray });

    page.drawText("TOTAL AMOUNT:", { x: width - 248, y: sY - 8, size: 8.5, font: fontBold, color: primaryDark });
    page.drawText(cleanPdfText(`${symbol}${totalAmount.toLocaleString('en-US', { minimumFractionDigits: 2 })}`), { x: width - 130, y: sY - 8, size: 9.5, font: fontBold, color: primaryDark });
    sY -= 18;

    if (amountPaid > 0) {
        page.drawText("Amount Paid:", { x: width - 248, y: sY - 4, size: 8, font: fontBold, color: successGreen });
        page.drawText(cleanPdfText(`-${symbol}${amountPaid.toLocaleString('en-US', { minimumFractionDigits: 2 })}`), { x: width - 130, y: sY - 4, size: 8, font: fontBold, color: successGreen });
        sY -= 14;

        page.drawText("BALANCE DUE:", { x: width - 248, y: sY - 4, size: 9, font: fontBold, color: accentIndigo });
        page.drawText(cleanPdfText(`${symbol}${balanceDue.toLocaleString('en-US', { minimumFractionDigits: 2 })}`), { x: width - 130, y: sY - 4, size: 10.5, font: fontBold, color: accentIndigo });
    }

    // Settlement & Terms Section on Left / Bottom
    const bankDetails = data.company?.bankAccountNumber ? {
        bankName: data.company.bankName || "Authorized Settlement Bank",
        accountName: data.company.bankAccountName || data.company.name,
        accountNumber: data.company.bankAccountNumber
    } : (data.manualAccountNumber ? {
        bankName: data.manualBankName || "Authorized Bank",
        accountName: data.manualAccountName || data.company?.name || "Merchant",
        accountNumber: data.manualAccountNumber
    } : null);

    if (bankDetails) {
        page.drawRectangle({
            x: 35,
            y: currentY - 70,
            width: 250,
            height: 70,
            color: bgLight,
            borderColor: borderGray,
            borderWidth: 1
        });

        page.drawText("SETTLEMENT INFORMATION", { x: 45, y: currentY - 14, size: 8, font: fontBold, color: primaryDark });
        page.drawText(cleanPdfText(`Bank: ${bankDetails.bankName}`), { x: 45, y: currentY - 28, size: 8, font: fontRegular, color: textDark });
        page.drawText(cleanPdfText(`Beneficiary: ${bankDetails.accountName}`), { x: 45, y: currentY - 41, size: 8, font: fontRegular, color: textDark });
        page.drawText(cleanPdfText(`Account No: ${bankDetails.accountNumber}`), { x: 45, y: currentY - 55, size: 8.5, font: fontBold, color: accentIndigo });
    }

    currentY = Math.min(summaryBoxY, currentY - 75) - 15;

    // Commercial Terms / Notes
    if (data.notes || data.paymentTerms) {
        const termsText = (data.paymentTerms || data.notes || "Standard commercial settlement terms apply.");
        page.drawText("COMMERCIAL TERMS & NOTES:", { x: 35, y: currentY, size: 7.5, font: fontBold, color: textMuted });
        page.drawText(cleanPdfText(termsText.substring(0, 150)), { x: 35, y: currentY - 12, size: 7.5, font: fontRegular, color: textDark });
        currentY -= 28;
    }

    // Official CraveBiz Security Footer
    page.drawLine({
        start: { x: 35, y: 38 },
        end: { x: width - 35, y: 38 },
        thickness: 0.75,
        color: borderGray
    });

    page.drawText(cleanPdfText("CraveBiZ Secure Document Protocol - Official Original Invoice Document - Authorized Workspace Protection"), {
        x: 35,
        y: 24,
        size: 7,
        font: fontRegular,
        color: textMuted
    });

    return await pdfDoc.save();
}

/**
 * Stores the official invoice PDF in memory, disk, and Supabase Storage.
 */
export async function storeInvoicePdf(
    invoiceId: string,
    companyId: string,
    pdfBuffer: Uint8Array,
    invoiceNumber?: string
): Promise<{ storagePath: string; publicUrl?: string }> {
    const safeInvNum = (invoiceNumber || invoiceId || 'document').replace(/[^a-zA-Z0-9_-]/g, '_');
    const fileName = `Invoice_${safeInvNum}_${invoiceId}.pdf`;
    const filePath = `invoices/${fileName}`;

    // 1. Cache in memory for instant delivery
    invoicePdfBufferCache.set(invoiceId, pdfBuffer);

    // 2. Persist to local disk storage
    try {
        const localPath = path.join(invoiceUploadsDir, fileName);
        fs.writeFileSync(localPath, Buffer.from(pdfBuffer));
    } catch (diskErr) {
        console.warn("[storeInvoicePdf] Local disk write warning:", diskErr);
    }

    // 3. Persist to Supabase Storage bucket ('documents' or 'invoices')
    let remotePublicUrl = "";
    try {
        const blob = new Blob([pdfBuffer], { type: 'application/pdf' });
        const { data, error } = await supabaseClient.storage
            .from('documents')
            .upload(filePath, blob, {
                contentType: 'application/pdf',
                upsert: true
            });

        if (!error && data) {
            const { data: urlData } = supabaseClient.storage
                .from('documents')
                .getPublicUrl(filePath);
            if (urlData?.publicUrl) {
                remotePublicUrl = urlData.publicUrl;
            }
        } else if (error) {
            console.warn("[storeInvoicePdf] Supabase storage upload notice:", error.message);
        }
    } catch (storageErr) {
        console.warn("[storeInvoicePdf] Supabase storage error:", storageErr);
    }

    return {
        storagePath: filePath,
        publicUrl: remotePublicUrl
    };
}

/**
 * Retrieves the stored official invoice PDF buffer.
 */
export async function getStoredInvoicePdf(invoiceId: string, companyId?: string): Promise<Uint8Array | null> {
    // 1. Check in-memory cache
    if (invoicePdfBufferCache.has(invoiceId)) {
        return invoicePdfBufferCache.get(invoiceId)!;
    }

    // 2. Check local disk
    try {
        if (fs.existsSync(invoiceUploadsDir)) {
            const files = fs.readdirSync(invoiceUploadsDir);
            const matchedFile = files.find(f => f.includes(invoiceId));
            if (matchedFile) {
                const diskBuffer = fs.readFileSync(path.join(invoiceUploadsDir, matchedFile));
                const uint8 = new Uint8Array(diskBuffer);
                invoicePdfBufferCache.set(invoiceId, uint8);
                return uint8;
            }
        }
    } catch (diskErr) {
        console.warn("[getStoredInvoicePdf] Disk read warning:", diskErr);
    }

    // 3. Check Supabase Storage
    try {
        const filePath = `invoices/Invoice_${invoiceId}.pdf`;
        const { data, error } = await supabaseClient.storage
            .from('documents')
            .download(filePath);
        if (!error && data) {
            const arrBuf = await data.arrayBuffer();
            const uint8 = new Uint8Array(arrBuf);
            invoicePdfBufferCache.set(invoiceId, uint8);
            return uint8;
        }
    } catch (storageErr) {
        // Fall through to null so caller can generate from DB
    }

    return null;
}

/**
 * Invalidates the cached PDF when an invoice is edited or updated.
 */
export function invalidateInvoicePdfCache(invoiceId: string): void {
    invoicePdfBufferCache.delete(invoiceId);
    invoiceDataCache.delete(invoiceId);
    try {
        if (fs.existsSync(invoiceUploadsDir)) {
            const files = fs.readdirSync(invoiceUploadsDir);
            for (const f of files) {
                if (f.includes(invoiceId)) {
                    fs.unlinkSync(path.join(invoiceUploadsDir, f));
                }
            }
        }
    } catch (e) {
        // Safe ignore
    }
}
